### ISSUE TITLE
Strings won't translate on get-text 5.4

### ISSUE THREAD

**Issue by UriLucioWald** [Belphemur/laravel-gettext#1]
Hi,
I used your package to migrate get-text to match Laravel 5.4, 
It's compiling but from some reason the translated strings won't appear echo __('hello') will output hello but not in the correct locale.
I did set the correct locale (checked in the controller `\LaravelGettext::getLocale()` return the expected result e.g: de_DE)
I am using exactly the same .po files I used in Laravel 5.3.
Any ideas ?

**Comment by redalpha01** [comment]
Are you using the _i("") helper instead of __("") as per 5.4 breaking changes?

**Comment by Belphemur** [comment]
See @redalpha01 comment.

I'm closing this

**Comment by lostcause** [comment]
Hate to re-open a closed issue, but I am having the same problem, and I am using the _i() helper.
I am using Laravel 5.4 in this project. I have another project on the same server, using Laravel 5.3 and get-text is working fine. 
I am using get-text as a handler.
