### ISSUE TITLE
Gettext in Console / Commands?

### ISSUE THREAD

**Issue by CedNet** [Belphemur/laravel-gettext#14]
Hi! This Gettext package doesn't translate stuff ran via the artisan schedule:run and any command there. Also not for phpunit tests.

Is there any way to force this package to load always no matter starter?

**Comment by Belphemur** [comment]
Hello,

The package is always loaded.

In case you run queue, cron, etc ... you need in the command/job itself to set the language (and set it back to what it was if you don't want to run in some issue).

Simply use the facade in your command/job `\LaravelGettext::setLocale($locale);`

**Comment by CedNet** [comment]
Thx for that info. My issue I just realized was that the default lang in the config for the package was english. I changed there to Swedish and it worked.

Please close this or remove fully. :)
