### ISSUE TITLE
Alias _ (single underscore) is not working

### ISSUE THREAD

**Issue by ClimberBear** [Belphemur/laravel-gettext#25]
Hi

I have a legacy code using a lot of gettext translations with alias _.

But this alias is not working in laravel-gettext

I have checked and it's defined in Support/helpers.php, in this way
```
if (!function_exists('_')) {
    /**
     * Generic translation function
     *
     * @param $message
     *
     * @return mixed
     */
    function _($message, $args = null)
    {
        return _i($message, $args);
    }
}
```
How can I get this working?

**Comment by Belphemur** [comment]
Hello,

Laravel use that function, I can't do anything about it since the framework is loaded before the plug-in.

If you check the Readme is written at the end of it. I advise you to use _i instead which is the function defined by the plug-in.

________________________________
