### ISSUE TITLE
default domain, locale in storage null?

### ISSUE THREAD

**Issue by dave-at-petabit** [Belphemur/laravel-gettext#3]
To make it work I have to add a few lines in this file:
laravel-gettext/src/Xinax/LaravelGettext/LaravelGettextServiceProvider.php

I have to add the following lines after this one:
```
            $storage = $app->make($configuration->get()->getStorage());

            $storage->setDomain($configuration->get()->getDomain());
            $storage->setEncoding($configuration->get()->getEncoding());
            $storage->setLocale($configuration->get()->getLocale());
```

Otherwise, I get this error: (empty locale)
Locale  is not supported

**Comment by Belphemur** [comment]
Are you using the Symfony translation module or the gettext php extension ?
