### ISSUE TITLE
Translation doesn't work on error page

### ISSUE THREAD

**Issue by sascha95** [Belphemur/laravel-gettext#5]
Hi there, I just tested the plugin and it works great.
But there seems to be a problem with error pages.
The text is translated on every page except the 404 page.

**Comment by Belphemur** [comment]
Hello,

Can you check if the middleware is loaded also for your Error Page ?

**Comment by sascha95** [comment]
Hi Belphemur,
thanks for the hint. The problem was that the the middleware is only loaded when a route is matched. If a NotFoundException is thrown the middlewares won't run.
I got it running by adding a fallback route so the middleware loads on the error page.
```
Route::fallback(function () {
    return view('errors.404');
});
```
I don't think if it's the best solution because i only want this for the 404 error page. Maybe i will find something better or someone else has a better solution.

**Comment by Belphemur** [comment]
One of the way (a little dirty to be honest) would be to run the code of 
the middleware directly in your view before rendering your strings.

It's only one method that is called to gather from the session the 
required language.
