### ISSUE TITLE
Target [Xinax\LaravelGettext\Translators\TranslatorInterface] is not instantiable while building [Xinax\LaravelGettext\LaravelGettext].

### ISSUE THREAD

**Issue by Snake231088** [Belphemur/laravel-gettext#8]
Command php artisan config:cache is used it throws the error:
Target [Xinax\LaravelGettext\Translators\TranslatorInterface] is not instantiable while building [Xinax\LaravelGettext\LaravelGettext].

It works if the alias in LaravelGettextServiceProvider is commented
// $aliasLoader->alias('LaravelGettext', \Xinax\LaravelGettext\Facades\LaravelGettext::class);
but in this case the alias LaravelGettext not work.

Please fix so it's possibile to use configuration cache feature.

Sotty my error configuration!

**Comment by lidoma** [comment]
I have the same issue. Any updates?
